apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-queue-consumer-keys
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
  target:
    name: prod-queue-consumer-keys
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /queue-consumer/prod
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "/queue-consumer/prod/(.*)"
            target: "$1"
