apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-queue-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hub-queue-consumer
  template:
    metadata:
      labels:
        app: hub-queue-consumer
    spec:
      containers:
        - name: hub-queue-consumer
          image: registry.digitalocean.com/portals-registry/portals-queue-consumer:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: prod-queue-consumer-keys
